spring:
  application:
    name: wetter-dashboard-api
  datasource:
    url: jdbc:mysql://localhost:3307/wetter_dashboard?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
