# Web Server
server.port=8080
spring.application.name=wetter-dashboard-api

# Wenn DB auf Rocky Linux liegt, nutze die IP des Servers!
spring.datasource.url=jdbc:mysql://localhost:3307/ventilation_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Einstellungen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
